default: &default
  adapter: postgresql
  port: 5432
  encoding: utf8
  username: slackapp
  pool: 5
  min_messages: log

development:
  <<: *default
  database: slackapp_development

test:
  <<: *default
  database: slackapp_test

production:
  <<: *default
  database: slackapp_production
