default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  min_messages: log


development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  min_messages: notice
