default: &default
  adapter:      <%= ENV['ADAPTER'] %>
  encoding:     utf8
  username:     <%= ENV['DATABASE_USER'] %>
  password:     <%= ENV['DATABASE_PASS'] %>
  pool:         <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url:          <%= ENV['DATABASE_URL'] %>
  min_messages: log


development:
  <<: *default

test:
  <<: *default
  username:
  password:
  database:     <%= ENV['DATABASE_NAME'] %>_<%= Rails.env %>

production:
  <<: *default
  min_messages: notice
