default: &default
  adapter: <%= ENV['ADAPTER'] %>
  encoding: utf8
  username: root
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>
  min_messages: log


development:
  <<: *default

test:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>_<%= Rails.env %>

production:
  <<: *default
  min_messages: notice
